"""initial_schema

Revision ID: 77716ec47547
Revises: 
Create Date: 2026-06-03 18:08:17.244230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77716ec47547'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('garments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('sub_category', sa.String(length=64), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=True),
    sa.Column('season', sa.JSON(), nullable=True),
    sa.Column('material', sa.String(length=64), nullable=True),
    sa.Column('style', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('wear_count', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_link', sa.String(length=512), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('garments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garments_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_garments_user_id'), ['user_id'], unique=False)

    op.create_table('wear_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('garment_id', sa.String(length=32), nullable=False),
    sa.Column('worn_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wear_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wear_logs_garment_id'), ['garment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wear_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wear_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wear_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_wear_logs_garment_id'))

    op.drop_table('wear_logs')
    with op.batch_alter_table('garments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garments_user_id'))
        batch_op.drop_index(batch_op.f('ix_garments_category'))

    op.drop_table('garments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    op.drop_table('users')
    # ### end Alembic commands ###
